name: Atualização diária de dados
on:
  push:
    branches:
      - main # ou outra branch que você queira monitorar
  schedule:
    - cron: '0 9 * * *' # executa diariamente às 9h (horário de Brasília)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        
      - name: Install renv
        run: Rscript -e 'install.packages("renv")'
        
      - name: Initialize renv
        run: Rscript -e 'renv::init()'

      - name: Install libcurl development package
        run: sudo apt-get install -y libcurl4-openssl-dev
      
      - name: Install packages
        run: Rscript -e 'renv::install()'

      - name: Run script
        run: Rscript FIIs.R

      - name: Set up Git
        env:
          GIT_AUTHOR_NAME: RoldanRamon
          GIT_AUTHOR_EMAIL: roldanramon83@gmail.com
          GIT_COMMITTER_NAME: RoldanRamon
          GIT_COMMITTER_EMAIL: roldanramon83@gmail.com
        run: |
          git config --local user.email "${GIT_AUTHOR_EMAIL}"
          git config --local user.name "${GIT_AUTHOR_NAME}"
          git config --local credential.helper store
          git remote set-url origin "https://$CHAVE@github.com/username/repo.git"
