name: Atualização diária de dados
on:
  push:
    branches:
      - main # ou outra branch que você queira monitorar
  schedule:
    - cron: '0 9 * * *' # executa diariamente às 9h (horário de Brasília)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@master
      - name: Install packages
        run: Rscript -e "install.packages(c('dplyr', 'ggplot2', 'rvest', 'janitor', 'readr', 'stringr'), repos = 'https://cloud.r-project.org')"

      - name: Run script
        run: Rscript ../FIIs.R # Substitua pelo caminho para o seu script R
