name: FIIs Report

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 9 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'main'
          node-version: 16
        
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.0'

      - name: Install renv
        run: Rscript -e 'install.packages("renv")'
        
      - name: Initialize renv
        run: Rscript -e 'renv::init()'

      - name: Install libcurl package
        run: sudo apt-get install -y libcurl4-openssl-dev
      
      - name: Restore R packages cache
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-renv-${{ hashFiles('renv.lock') }}
          restore-keys: ${{ runner.os }}-renv-

      - name: Install packages
        run: Rscript -e 'renv::restore()'

      - name: Run Rscript to Web Scrapping
        run: Rscript FIIs.R
        
      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL }}
          password: ${{ secrets.SENHA_DO_EMAIL }}
          subject: Relatório de Fundos Imobiliários (FIIS)
          body: |
            **Prezado(a), tudo bem?**
            
            Compartilho anexo relatório atualizado dos fundos imobiliários.
            
            Os principais tipos de FIIs são:
            
            🏗️ **FIIs de tijolo**: Fundos que aplicam o seu patrimônio na construção e/ou exploração comercial de imóveis físicos, como galpões, prédios de escritórios, shoppings, etc.

            📃 **FIIs de papel**: Aplicam o patrimônio dos seus cotistas em instrumentos financeiros do setor imobiliário, tais como CRIs, LCIs e LHs.

            🏙️ **Fundos de Fundos (FoFs)**: São aqueles que aplicam o patrimônio de seus cotistas exclusivamente em cotas de outros Fundos Imobiliários, viabilizando a diversificação com um único investimento.

            🚜 **Fiagros**: O patrimônio dos cotistas é investido visando financiar as cadeias produtivas agroindustriais por meio de participações, propriedades rurais, terras ou imóveis agrícolas, além de certificados de recebíveis.

            **Breve explicação das colunas do relatório:**

            **papel**: O código ou identificador do fundo imobiliário.  
            **segmento**: O segmento ou tipo de investimento em que o fundo imobiliário está enquadrado.  
            **cotacao**: O valor atual da cota do fundo imobiliário.  
            **ffo_yield**: O rendimento FFO (Funds From Operations) do fundo imobiliário em relação à cotação.  
            **dividend_yield**: O rendimento de dividendos do fundo imobiliário em relação à cotação.  
            **p_vp**: O preço-valor patrimonial (P/VP) do fundo imobiliário.  
            **valor_de_mercado**: O valor de mercado total do fundo imobiliário.  
            **liquidez**: A liquidez do fundo imobiliário, indicando a quantidade de negociações realizadas.  
            **qtd_de_imoveis**: A quantidade de imóveis que compõem o fundo imobiliário.  
            **preco_do_m2**: O preço médio do metro quadrado dos imóveis do fundo.  
            **aluguel_por_m2**: O valor médio de aluguel por metro quadrado dos imóveis do fundo.  
            **cap_rate**: A taxa de capitalização do fundo imobiliário.  
            **vacancia_media**: A taxa média de vacância dos imóveis do fundo.  
            **endereco**: O endereço dos imóveis do fundo.  
            **data_atualizacao**: A data de atualização dos dados na tabela.
            
            **Aviso**: Este estudo não é uma recomendação de compra ou venda, mas sim um estudo teórico de data science. O mercado financeiro é volátil e envolve riscos, por isso estude bem antes de realizar operações e converse com seu consultor.

            Desde já agradeço pela atenção e qualquer coisa permaneço à disposição.

            **Cordialmente,**  
            Ramon Roldan.
          convert_markdown: true
          to: ${{ secrets.EMAIL }}
          Bcc: ${{ secrets.EMAIL_INTERASSADOS }}
          from: ${{ secrets.EMAIL }}
          content_type: text/html
          attachments: |
            fiis.xlsx

      - name: Commit Files
        run: |
          git config --local user.email "roldanramon83@gmail.com"
          git config --local user.name "Ramon Roldan de Lara"
          git add --all
          git commit -am "add data"
          git push 
