name: Atualização diária de dados
on:
  push:
    branches:
      - main # ou outra branch que você queira monitorar
  schedule:
    - cron: '0 9 * * *' # executa diariamente às 9h (horário de Brasília)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.0'
          include-tinytex: true
          cran: http://cran.rstudio.com/
        
      - name: Install packages
        run: Rscript -e "install.packages(c('dplyr','rvest', 'janitor', 'readr'))"

      - name: Run script
        run: Rscript FIIs.R # Substitua pelo caminho para o seu script R
