name: FIIs Report

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 9 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'main'
        
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.0'

      - name: Install renv
        run: Rscript -e 'install.packages("renv")'
        
      - name: Initialize renv
        run: Rscript -e 'renv::init()'

      - name: Install libcurl package
        run: sudo apt-get install -y libcurl4-openssl-dev
      
      - name: Restore R packages cache
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-renv-${{ hashFiles('renv.lock') }}
          restore-keys: ${{ runner.os }}-renv-

      - name: Install packages
        run: Rscript -e 'renv::restore()'

      - name: Run Rscript to Web Scrapping
        run: Rscript FIIs.R
        
      - name: Send Email with Action
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL }}
          password: ${{ secrets.SENHA_DO_EMAIL }}
          subject: Relatório de Fundos Imobiliários (FIIS)
          body: 'Oi, tudo bem?\n\nConforme conversamos compartilho relatório que elaborei para entender o cenário atual dos Fundos Imobiliários (FIIS).\nEste estudo não é uma recomendação de compra ou venda. O mercado financeiro é volátil e envolve riscos, por isso estude bem antes de realizar operações e converse com seu consultor.\n\nDesde já agradeço pela atenção e qualquer coisa permaneço à disposição.\n\nCordialmente,\nRamon Roldan de Lara.'
          to: ${{ secrets.EMAIL_INTERESSADOS }}
          from: ${{ secrets.EMAIL }}
          content_type: text/plain
          attachments: |
            fiis.csv  

      - name: Commit Files
        run: |
          git config --local user.email "roldanramon83@gmail.com"
          git config --local user.name "Ramon Roldan de Lara"
          git add --all
          git commit -am "add data"
          git push 

