name: Atualização diária de dados

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 9 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'main'
        
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.0'

      - name: Install renv
        run: Rscript -e 'install.packages("renv")'
        
      - name: Initialize renv
        run: Rscript -e 'renv::init()'

      - name: Install libcurl development package
        run: sudo apt-get install -y libcurl4-openssl-dev
      
      - name: Restore R packages cache
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-renv-${{ hashFiles('renv.lock') }}
          restore-keys: ${{ runner.os }}-renv-

      - name: Install packages
        run: Rscript -e 'renv::restore()'

      - name: Run Rscript to Web Scrapping
        run: Rscript FIIs.R
        
      - name: Send Email with Python
        run: python send_email.py

      - name: Commit files
        run: |
          git config --local user.email "roldanramon83@gmail.com"
          git config --local user.name "Ramon Roldan de Lara"
          git add --all
          git commit -am "add data"
          git push 

